// lib/raceData.ts

export const raceDataGroups = [
  {
    zone: "Zone 1",
    sub: "The RESISTANCE",
    activities: [
      {
        activity: "Run 1",
        female: "1200m",
        male: "1600m",
        mixed: "2000m",
        type: "run",
      },
      {
        activity: "Kettlebell Carry",
        female: "16kg x 2, 160m",
        male: "24kg x 2, 160m",
        mixed: "24kg x 2, 240m",
      },
      {
        activity: "Tyre Flip",
        female: "60kg, 80m",
        male: "80kg, 80m",
        mixed: "80kg, 160m",
      },
    ],
  },
  {
    zone: "Zone 2",
    sub: "The CADENCE",
    activities: [
      {
        activity: "Run 2",
        female: "1200m",
        male: "1600m",
        mixed: "2000m",
        type: "run",
      },
      {
        activity: "Dumbbell Snatch",
        female: "9kg, 70rep",
        male: "15kg, 70rep",
        mixed: "15kg, 80rep",
      },
      { activity: "Burpee", female: "80m", male: "90m", mixed: "100m" },
      {
        activity: "Sandbag Lunges",
        female: "10kg, 80m",
        male: "20kg, 80m",
        mixed: "20kg, 160m",
      },
    ],
  },
  {
    zone: "Zone 3",
    sub: "The ASCENT",
    activities: [
      {
        activity: "Run 3",
        female: "1200m",
        male: "1600m",
        mixed: "2000m",
        type: "run",
      },
      {
        activity: "Dumbbell Press",
        female: "5kg X 2, 30 rep",
        male: "10kg X 2, 30 rep",
        mixed: "10kg X 2, 40 rep",
      },
      {
        activity: "Kettlebell Squats",
        female: "12kg, 70rep",
        male: "16kg, 70rep",
        mixed: "16kg, 80rep",
      },
      { activity: "Bear Crawl", female: "120m", male: "160m", mixed: "200m" },
      {
        activity: "Dumbbell Push",
        female: "6kg X 2, 80 rep",
        male: "12.5kg X 2, 80 rep",
        mixed: "12.5kg X 2, 100 rep",
      },
    ],
  },
  {
    zone: "Finish",
    sub: "Final Push",
    activities: [
      {
        activity: "Run 4",
        female: "1200m",
        male: "1600m",
        mixed: "2000m",
        type: "run",
      },
    ],
  },
];

export const exerciseCards = [
  {
    title: "Kettlebell Carry",
    zone: "Zone 1",
    sub: "The RESISTANCE",
    img: "/KC.jpeg",
    female: "16kg x 2",
    male: "24kg x 2",
    mixed: "24kg x 2",
    reps: "160m / 240m",
  },
  {
    title: "Tyre Flip",
    zone: "Zone 1",
    sub: "The RESISTANCE",
    img: "/TF.jpeg",
    female: "60kg",
    male: "80kg",
    mixed: "80kg",
    reps: "80m / 160m",
  },
  {
    title: "Dumbbell Snatch",
    zone: "Zone 2",
    sub: "The CADENCE",
    img: "/DS.jpeg",
    female: "9kg",
    male: "15kg",
    mixed: "15kg",
    reps: "70 / 80 Reps",
  },
  {
    title: "Burpee",
    zone: "Zone 2",
    sub: "The CADENCE",
    img: "/BR.jpeg",
    female: "80m",
    male: "90m",
    mixed: "100m",
    reps: "Distance",
  },
  {
    title: "Sandbag Lunges",
    zone: "Zone 2",
    sub: "The CADENCE",
    img: "/SL.jpeg",
    female: "10kg",
    male: "20kg",
    mixed: "20kg",
    reps: "80m / 160m",
  },
  {
    title: "Dumbbell Press",
    zone: "Zone 3",
    sub: "The ASCENT",
    img: "/DP.jpeg",
    female: "5kg x 2",
    male: "10kg x 2",
    mixed: "10kg x 2",
    reps: "30 / 40 Reps",
  },
  {
    title: "Kettlebell Squats",
    zone: "Zone 3",
    sub: "The ASCENT",
    img: "/KS.jpeg",
    female: "12kg",
    male: "16kg",
    mixed: "16kg",
    reps: "70 / 80 Reps",
  },
  {
    title: "Bear Crawl",
    zone: "Zone 3",
    sub: "The ASCENT",
    img: "/BC.jpeg",
    female: "120m",
    male: "160m",
    mixed: "200m",
    reps: "Distance",
  },
  {
    title: "Dumbbell Push",
    zone: "Zone 3",
    sub: "The ASCENT",
    img: "/DPR.jpeg",
    female: "6kg x 2",
    male: "12.5kg x 2",
    mixed: "12.5kg x 2",
    reps: "80 / 100 Reps",
  },
];
